# Generated by Django 3.2.9 on 2021-12-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20211205_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='posts',
        ),
    ]
