# Generated by Django 3.2.9 on 2021-12-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_active',
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
