# Generated by Django 3.2.9 on 2021-12-09 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20211208_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='liked_post', to='network.Post', verbose_name='liked Posts'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker_user', to=settings.AUTH_USER_MODEL, verbose_name='liker'),
        ),
    ]
