# Generated by Django 3.2.9 on 2021-12-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211209_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='network.Post', verbose_name='liked Posts'),
        ),
    ]
