# Generated by Django 3.2.9 on 2022-01-04 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_like_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-creation_date',), 'verbose_name': 'Follow', 'verbose_name_plural': 'Follows'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-creation_date',), 'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate,
                # new table name from like_post._meta.db_table.
                migrations.RunSQL(
                    sql="ALTER TABLE network_like_posts RENAME TO network_like_post",
                    reverse_sql="ALTER TABLE network_like_post RENAME TO network_like_posts",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="like_post",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "like",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="network.like",
                            ),
                        ),
                        (
                            "post",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="network.post",
                            ),
                        ),
                    ],
                    options={
                        # 'verbose_name': 'Liked Post',
                        # 'verbose_name_plural': 'Liked Posts',
                        "db_table": "network_like_post",
                        # 'ordering': ('-time_stamp',),
                    },
                ),
                migrations.AlterField(
                    model_name="like",
                    name="posts",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="liked_posts",
                        to="network.Post",
                        verbose_name="liked Posts",
                        through="network.like_post",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="like_post",
            name="time_stamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="time stamp"),
        ),
    ]
