# Generated by Django 3.2.9 on 2022-01-04 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20220104_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like_post',
            options={'ordering': ('-time_stamp',)},
        ),
    ]
