# Generated by Django 3.2.9 on 2022-01-05 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_like_post_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like_post',
            new_name='LikePost',
        ),
    ]
