name: deploy
on: 
  push:
    paths:
      - '.github/**'
      - '**/Dockerfile'
      - '**/Dockerfile*'

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          docker_heroku_process_type: web
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          DEBUG: ${{ secrets.DEBUG }}
          # db
          POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        run: heroku container:push web --app --recursive

  # custom-deploy:
  #   # The `needs` is added to bypass:
  #   # "Your account has reached its concurrent builds limit"
  #   needs: heroku-deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Heroku login credentials
  #       run: |
  #         cat > ~/.netrc <<EOF
  #           machine api.heroku.com
  #             login $HEROKU_EMAIL
  #             password $HEROKU_API_KEY
  #           machine git.heroku.com
  #             login $HEROKU_EMAIL
  #             password $HEROKU_API_KEY
  #         EOF
  #       env:
  #         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #         HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
  #     - name: Add Heroku remote
  #       run: heroku git:remote --app $HEROKU_APP_NAME
  #       env:
  #         HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  #     - name: Push to Heroku
  #       run: git push heroku main